USE ROLE F1_&{v_env}_SNO_UCE_ADMIN;

--ONBOARD SYSTEM USER FOR THE PROJECT THROUGH GMT, IF NEEDED
ALTER USER "&{v_sys_account}@NOVARTIS.NET" SET 
  PASSWORD = '&{v_PASSWORD}'
  MUST_CHANGE_PASSWORD = FALSE
  DEFAULT_WAREHOUSE = &{v_PROJECT}_WH_M
  DEFAULT_ROLE = F1_&{v_env}_SNO_&{v_PROJECT}_DATA_ENGINEER
;