use role F1_&{v_env}_SNO_UCE_ADMIN;

USE DATABASE CURATED_RAW;
use warehouse &{v_PROJECT}_WH_M;

CREATE SCHEMA IF NOT EXISTS CURATED_RAW.&{SUB_DATA_DOMAIN}_UNIFIED;
CREATE SCHEMA IF NOT EXISTS &{DATA_DOMAIN}_REFINEMENT.&{SUB_DATA_DOMAIN}_CONSOL;
-- repeat above command to create all requested SUB_DATA_DOMAINs schemas

CREATE SCHEMA IF NOT EXISTS &{DATA_DOMAIN}_REFINEMENT.&{SUB_DATA_DOMAIN};
-- repeat above command to create all requested SUB_DATA_DOMAINs schemas

USE DATABASE CURATED_RAW;

USE SCHEMA &{SUB_DATA_DOMAIN}_UNIFIED;

CREATE STAGE IF NOT EXISTS &{SUB_DATA_DOMAIN}_STAGE
	STORAGE_INTEGRATION = &{STORAGE_INTEGRATION}
	URL = '&{v_S3_UNIFIED_FOLDER}'
	ENCRYPTION=(TYPE='AWS_SSE_KMS');

CREATE OR REPLACE FILE FORMAT &{SUB_DATA_DOMAIN}_&(FILE_FORMAT_TYPE)
    TYPE = &(FILE_FORMAT_TYPE);

grant role F1_&{v_env}_SNO_&{v_PROJECT}_DATA_ENGINEER to role F1_&{v_env}_SNO_UCE_ADMIN;

grant role F1_&{v_env}_SNO_&{v_PROJECT}_DATA_ANALYST to role F1_&{v_env}_SNO_&{v_PROJECT}_DATA_ENGINEER;


GRANT USAGE on database CURATED_RAW to role F1_&{v_env}_SNO_&{v_PROJECT}_DATA_ANALYST;
GRANT USAGE on database &{DATA_DOMAIN}_REFINEMENT to role F1_&{v_env}_SNO_&{v_PROJECT}_DATA_ANALYST;


GRANT USAGE,MONITOR ON WAREHOUSE &{v_PROJECT}_WH_M TO ROLE F1_&{v_env}_SNO_&{v_PROJECT}_DATA_ANALYST;
GRANT USAGE,MONITOR ON WAREHOUSE &{v_PROJECT}_WH_S TO ROLE F1_&{v_env}_SNO_&{v_PROJECT}_DATA_ANALYST;


GRANT USAGE,MONITOR ON SCHEMA CURATED_RAW.&{SUB_DATA_DOMAIN}_UNIFIED TO ROLE F1_&{v_env}_SNO_&{v_PROJECT}_DATA_ANALYST;

GRANT USAGE,MONITOR ON SCHEMA &{DATA_DOMAIN}_REFINEMENT.&{SUB_DATA_DOMAIN}_CONSOL TO ROLE F1_&{v_env}_SNO_&{v_PROJECT}_DATA_ANALYST;

GRANT USAGE,MONITOR ON SCHEMA &{DATA_DOMAIN}_REFINEMENT.&{SUB_DATA_DOMAIN} TO ROLE F1_&{v_env}_SNO_&{v_PROJECT}_DATA_ANALYST;

GRANT USAGE,MONITOR ON SCHEMA CURATED_RAW.&{SUB_DATA_DOMAIN}_UNIFIED TO ROLE F1_&{v_env}_SNO_&{v_PROJECT}_DATA_ENGINEER;

GRANT CREATE STAGE ON SCHEMA CURATED_RAW.&{SUB_DATA_DOMAIN}_UNIFIED TO ROLE F1_&{v_env}_SNO_&{v_PROJECT}_DATA_ENGINEER;
GRANT CREATE TABLE ON SCHEMA CURATED_RAW.&{SUB_DATA_DOMAIN}_UNIFIED TO ROLE F1_&{v_env}_SNO_&{v_PROJECT}_DATA_ENGINEER ;
GRANT CREATE EXTERNAL TABLE ON SCHEMA CURATED_RAW.&{SUB_DATA_DOMAIN}_UNIFIED TO ROLE F1_&{v_env}_SNO_&{v_PROJECT}_DATA_ENGINEER ;
GRANT CREATE VIEW ON SCHEMA CURATED_RAW.&{SUB_DATA_DOMAIN}_UNIFIED TO ROLE F1_&{v_env}_SNO_&{v_PROJECT}_DATA_ENGINEER ;
GRANT CREATE TEMPORARY TABLE ON SCHEMA CURATED_RAW.&{SUB_DATA_DOMAIN}_UNIFIED TO ROLE F1_&{v_env}_SNO_&{v_PROJECT}_DATA_ENGINEER ;
GRANT CREATE MATERIALIZED VIEW ON SCHEMA CURATED_RAW.&{SUB_DATA_DOMAIN}_UNIFIED TO ROLE F1_&{v_env}_SNO_&{v_PROJECT}_DATA_ENGINEER ;
GRANT CREATE SEQUENCE ON SCHEMA CURATED_RAW.&{SUB_DATA_DOMAIN}_UNIFIED TO ROLE F1_&{v_env}_SNO_&{v_PROJECT}_DATA_ENGINEER ;
GRANT CREATE FUNCTION ON SCHEMA CURATED_RAW.&{SUB_DATA_DOMAIN}_UNIFIED TO ROLE F1_&{v_env}_SNO_&{v_PROJECT}_DATA_ENGINEER ;
GRANT CREATE PROCEDURE ON SCHEMA CURATED_RAW.&{SUB_DATA_DOMAIN}_UNIFIED TO ROLE F1_&{v_env}_SNO_&{v_PROJECT}_DATA_ENGINEER ;

GRANT CREATE TABLE ON SCHEMA &{DATA_DOMAIN}_REFINEMENT.&{SUB_DATA_DOMAIN}_CONSOL TO ROLE F1_&{v_env}_SNO_&{v_PROJECT}_DATA_ENGINEER ;
GRANT CREATE EXTERNAL TABLE ON SCHEMA &{DATA_DOMAIN}_REFINEMENT.&{SUB_DATA_DOMAIN}_CONSOL TO ROLE F1_&{v_env}_SNO_&{v_PROJECT}_DATA_ENGINEER ;
GRANT CREATE VIEW ON SCHEMA &{DATA_DOMAIN}_REFINEMENT.&{SUB_DATA_DOMAIN}_CONSOL TO ROLE F1_&{v_env}_SNO_&{v_PROJECT}_DATA_ENGINEER ;
GRANT CREATE TEMPORARY TABLE ON SCHEMA &{DATA_DOMAIN}_REFINEMENT.&{SUB_DATA_DOMAIN}_CONSOL TO ROLE F1_&{v_env}_SNO_&{v_PROJECT}_DATA_ENGINEER ;
GRANT CREATE MATERIALIZED VIEW ON SCHEMA &{DATA_DOMAIN}_REFINEMENT.&{SUB_DATA_DOMAIN}_CONSOL TO ROLE F1_&{v_env}_SNO_&{v_PROJECT}_DATA_ENGINEER ;
GRANT CREATE SEQUENCE ON SCHEMA &{DATA_DOMAIN}_REFINEMENT.&{SUB_DATA_DOMAIN}_CONSOL TO ROLE F1_&{v_env}_SNO_&{v_PROJECT}_DATA_ENGINEER ;
GRANT CREATE FUNCTION ON SCHEMA &{DATA_DOMAIN}_REFINEMENT.&{SUB_DATA_DOMAIN}_CONSOL TO ROLE F1_&{v_env}_SNO_&{v_PROJECT}_DATA_ENGINEER ;
GRANT CREATE PROCEDURE ON SCHEMA &{DATA_DOMAIN}_REFINEMENT.&{SUB_DATA_DOMAIN}_CONSOL TO ROLE F1_&{v_env}_SNO_&{v_PROJECT}_DATA_ENGINEER ;

GRANT CREATE TABLE ON SCHEMA &{DATA_DOMAIN}_REFINEMENT.&{SUB_DATA_DOMAIN} TO ROLE F1_&{v_env}_SNO_&{v_PROJECT}_DATA_ENGINEER ;
GRANT CREATE EXTERNAL TABLE ON SCHEMA &{DATA_DOMAIN}_REFINEMENT.&{SUB_DATA_DOMAIN} TO ROLE F1_&{v_env}_SNO_&{v_PROJECT}_DATA_ENGINEER ;
GRANT CREATE VIEW ON SCHEMA &{DATA_DOMAIN}_REFINEMENT.&{SUB_DATA_DOMAIN} TO ROLE F1_&{v_env}_SNO_&{v_PROJECT}_DATA_ENGINEER ;
GRANT CREATE TEMPORARY TABLE ON SCHEMA &{DATA_DOMAIN}_REFINEMENT.&{SUB_DATA_DOMAIN} TO ROLE F1_&{v_env}_SNO_&{v_PROJECT}_DATA_ENGINEER ;
GRANT CREATE MATERIALIZED VIEW ON SCHEMA &{DATA_DOMAIN}_REFINEMENT.&{SUB_DATA_DOMAIN} TO ROLE F1_&{v_env}_SNO_&{v_PROJECT}_DATA_ENGINEER ;
GRANT CREATE SEQUENCE ON SCHEMA &{DATA_DOMAIN}_REFINEMENT.&{SUB_DATA_DOMAIN} TO ROLE F1_&{v_env}_SNO_&{v_PROJECT}_DATA_ENGINEER ;
GRANT CREATE FUNCTION ON SCHEMA &{DATA_DOMAIN}_REFINEMENT.&{SUB_DATA_DOMAIN} TO ROLE F1_&{v_env}_SNO_&{v_PROJECT}_DATA_ENGINEER ;
GRANT CREATE PROCEDURE ON SCHEMA &{DATA_DOMAIN}_REFINEMENT.&{SUB_DATA_DOMAIN} TO ROLE F1_&{v_env}_SNO_&{v_PROJECT}_DATA_ENGINEER ;