USE ROLE F1_&{v_env}_SNO_UCE_ADMIN;

CREATE WAREHOUSE IF NOT EXISTS &{v_PROJECT}_WH_S WITH 
    WAREHOUSE_SIZE = 'SMALL' 
    WAREHOUSE_TYPE = 'STANDARD' 
    AUTO_SUSPEND = 300 
    AUTO_RESUME = TRUE 
    MIN_CLUSTER_COUNT = 1 
    MAX_CLUSTER_COUNT = 1 
    SCALING_POLICY = 'STANDARD'
    INITIALLY_SUSPENDED = TRUE
;

CREATE WAREHOUSE IF NOT EXISTS &{v_PROJECT}_WH_M WITH 
    WAREHOUSE_SIZE = 'MEDIUM' 
    WAREHOUSE_TYPE = 'STANDARD' 
    AUTO_SUSPEND = 300 
    AUTO_RESUME = TRUE 
    MIN_CLUSTER_COUNT = 1 
    MAX_CLUSTER_COUNT = 1 
    SCALING_POLICY = 'STANDARD'
    INITIALLY_SUSPENDED = TRUE
;


call MONITOR_DB.WAREHOUSE_TAG_CATALOG.CREATE_RESOURCE_MONITOR('&{v_PROJECT}_RM', '500','75','90');

call MONITOR_DB.WAREHOUSE_TAG_CATALOG.ASSIGN_RESOURCE_MONITOR('&{v_PROJECT}_RM','&{v_PROJECT}_WH_M');

call MONITOR_DB.WAREHOUSE_TAG_CATALOG.ASSIGN_RESOURCE_MONITOR('&{v_PROJECT}_RM','&{v_PROJECT}_WH_S');
